---
title: "Reference Free Cell Correction Comparison in Cord Blood"
author: "Meg Jones and Rachel Edgar"
date: "22/11/2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, include=FALSE,  message=FALSE}
## Define consistent color scheme for methods

library(ggsci)
library(ggplot2)
library(ggridges)
library(knitr)
library(kableExtra)
library(dplyr)
library(reshape2)


## method colors
myColors <- c("gold","goldenrod",
              "#2171b5","#6baed6","#6baed6",
              "#9467BDFF","#D62728FF",
              "#238443","#78c679","#addd8e","#d9f0a3",
              "#dd3497","#fa9fb5","grey")

color_possibilities<-c("FACS - PCA - Gold-Standard","FACS - Drop One Cell Type",
                       "Deconvolution - PCA","Deconvolution - Drop One Cell Type","Deconvolution - Counts",
                       "ReFACTor","RefFreeCellMix",
                       "SVA - Supervised GA","SVA - Unsupervised GA",
                       "SVA - Supervised Sex","SVA - Unsupervised Sex",
                       "RUV - GA", "RUV - Sex",
                       "Uncorrected")

names(myColors) <- color_possibilities
fillscale <- scale_fill_manual(name="Method",
                               values = myColors, drop = T)


### Cell type colors
myColors_cell <- c("#fc4e2a","orange", "#cb181d","#1d91c0", "#7fcdbb", "#78c679","#238443")

color_possibilities_cell<-c("Monocytes","Granulocytes", "nRBCs","NK Cells", "B Cells", "CD4 T Cells","CD8 T Cells")

names(myColors_cell) <- color_possibilities_cell
fillscale_cell <- scale_fill_manual(name="Cell Type",
                               values = myColors_cell, drop = T)


### nice theme
th <-   theme(axis.text=element_text(size=12),
        axis.title=element_text(size=14),
        strip.text.x = element_text(size = 12),
        legend.text=element_text(size=12),
        legend.title=element_text(size=14))

```

```{r, echo=FALSE,  message=FALSE}
## load meta data
meta_cord<-read.csv("/big_data/redgar/cordblood/24_wholebloods_samplesheet.csv")

meta_celltypes<-meta_cord[,c(12,13,5:11)]
female<-paste(round((length(which(meta_cord$Sex=="F"))/24)*100, 2),"%", sep="")
GA<-round(mean(meta_cord$GA), 2)


meta_celltypes<-meta_cord[,c(5:11)]
mean_celltypes<-t(as.data.frame(round(colMeans(meta_celltypes),2)))
sd_celltypes<-t(as.data.frame(round(apply(meta_celltypes,2, sd),2)))
mean_celltypes<-t(as.data.frame(paste(mean_celltypes,"% (",sd_celltypes,")",  sep="")))

lab<-data.frame(celltype="Mean % (sd)")

meta_summary<-t(data.frame(Female=female,Mean_GA=GA,lab, mean_celltypes ))
rownames(meta_summary)<-c("Female","Mean Gestational Age","FACS Cell Composition","Monocytes","Granulocytes", "nRBCs","NK Cells", "B Cells", "CD4 T Cells","CD8 T Cells")
meta_summary<-as.data.frame(meta_summary)
meta_summary$genR<-""
colnames(meta_summary)<-c("UBC data (n=24)", "GenR (n=196)")


kable(meta_summary, format="latex", booktabs = T, caption = "Cohort Description")%>%
  kable_styling(font_size = 12,(latex_options = c("HOLD_position")))%>%
  row_spec(3, bold = T)%>%
  add_indent(c(4:10))

```
\pagebreak

\newpage
```{r, echo=FALSE,  message=FALSE}
methods_table<-read.csv("methods_table.csv")
colnames(methods_table)<-c("Method","Explanation","Type","Phenotype Required","Citation" )

kable(methods_table, format="latex", booktabs = T, caption = "Method name used in comparison, explanation of method, whether it is reference free, reference based or semi reference free, whether the method models with a given phenotype for EWAS, and the relevant citation for the method.")%>%
  kable_styling(font_size = 7,(latex_options = c("HOLD_position")))%>%
  column_spec(column=2, width = "10em")

```
\pagebreak

\newpage
```{r R21, fig.width=8,  fig.height=5, echo=FALSE,  message=FALSE,fig.cap='Variance explained in each FACS cell count by models using components from several cell type estimation methods. Models were fit used a nested-models likelihood ratio test. Components from each method were included if they significantly (p<0.05) improved model fit.'}
load("~/referencefree_cord_blood/R2_plot.RData")
levels(plt_r2$facs_celltype)<-c("Monocytes","Granulocytes", "nRBCs","NK Cells", "B Cells", "CD4 T Cells","CD8 T Cells")

ggplot(plt_r2, aes(facs_celltype, R2_LRT, fill=method))+geom_point(shape=21, color="black", size=2, position=position_jitter(width=0.2))+theme_bw()+
  fillscale+
  ylab("R2 (FACS Cell Type Variance Accounted for)")+xlab("FACS Cell Type")+th+
  theme(axis.text.x = element_text(size=12,angle = 45, hjust = 1))


ggsave("figures/Figure1R2.pdf", width = 9, height = 5, units = "in")
```
\pagebreak


\newpage
```{r R22, fig.width=8,  fig.height=7, echo=FALSE,  message=FALSE,fig.cap='Variance explained in each FACS cell count by models using components from several cell type estimation methods. Models were fit used a nested-models likelihood ratio test. Models include components from each method if the component had significant likelihood ratio test p value (p<0.05). Expect for deconvolution - counts which gives measure of each cell type and R2 values are only for models with the deconvolution predicted cell type. Points represent each of 7 cell types, split by the method.'}
## mean boxplot
ggplot(plt_r2, aes(reorder(method, R2_LRT, FUN=median), R2_LRT))+geom_boxplot(outlier.size=NA, fill="grey95")+
  geom_point(aes(fill=facs_celltype),shape=21, color="black", size=2.25, position=position_jitter(width=0.2))+theme_bw()+
  ylab("R2 (FACS Cell Type Variance Accounted for)")+fillscale_cell+xlab("")+th+
  theme(axis.text.x = element_text(size=12,color="black",angle = 90, hjust = 1))

ggsave("figures/Figure2R2.pdf", width = 8, height = 7, units = "in")


```
\pagebreak

\newpage
```{r mae, fig.width=13,  fig.height=11, echo=FALSE,  message=FALSE,fig.cap='Mean absolute error(MAE) of CpGs compared to the gold-standard FACS-PCA corrected beta values. Errors shown are an average of all CpGs MAE. Boxes are coloured by the discretized MAE value to highlight method performance.'}
load("~/referencefree_cord_blood/error_all.RData")

error_all_unique<-error_all[!duplicated(error_all$mn_cpg_mae),]
error_all_unique<-error_all_unique[-1,]

error_all_unique$col_error<-cut(error_all_unique$mn_cpg_mae, c(0,0.001, 0.005,0.0075,0.01), right=FALSE, labels=c("<0.001","<0.005","<0.0075",">0.0075"))

ggplot(error_all_unique, aes(method_1,method_2, fill = col_error)) +
  geom_tile(color = "black",size=0.5) +
  geom_text(aes(label = round(mn_cpg_mae,3)), color="black", size=5)+theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_blank())+
  scale_fill_manual(values=c("#084594","#4292c6","#9ecae1","#deebf7"), name="MAE")+th+
  theme(axis.text.y=element_text(size=12,color="black"),
        axis.text.x = element_text(size=12,color="black",angle = 90, hjust = 1),
        panel.border = element_blank(),
        axis.ticks=element_blank())+xlab("")+ylab("")

ggsave("figures/maehalf.pdf", width = 13, height = 11, units = "in")

```
\pagebreak

\newpage
```{r correlation, fig.width=12,  fig.height=10, echo=FALSE,  message=FALSE, fig.cap='Distributions of correlation of beta values across samples at each CpG. Betas across samples were correlated between each method and the gold-standard FACS-PCA corrected betas. Vertical blue line shows the median correlation across all CpGs for the Deconvolution PCA corrected betas.'}
load("~/referencefree_cord_blood/correlation_distributions.RData")

decon_med_cor<-median(cor_to_GS$correlation[which(cor_to_GS$method=="Deconvolution - PCA")])

ggplot(cor_to_GS, aes(x = correlation, y = reorder(method, correlation, FUN=median), fill=method)) +
  geom_density_ridges(scale = 4) + theme_ridges() +
fillscale   +xlab("CpG Correlation to Gold Standard Betas")+ylab("")+th+
  geom_vline(xintercept=decon_med_cor, color="#2171b5", size=0.75)

ggsave("figures/Figure3cor.pdf", width = 12, height = 10, units = "in")
```
\pagebreak

\newpage
```{r deconvolutioncounts, fig.width=9,  fig.height=11, echo=FALSE,  message=FALSE, fig.cap='Varibility in the predicted cell counts on data already corrected for cell type. Across methods the deconvolution predicted cell counts for each cell type are shown. '}

load("/big_data/reffree/adj.residuals.sva.unsup.sex_predicted_cell_types.Rdata")
sva.unsup.sex<- est_cell_counts
load("/big_data/reffree/adj.residuals.sva.unsup.ga_predicted_cell_types.Rdata")
sva.unsup.ga<- est_cell_counts
load("/big_data/reffree/adj.residuals.sva.sup.sex_predicted_cell_types.Rdata")
sva.sup.sex<- est_cell_counts
load("/big_data/reffree/adj.residuals.sva.sup.ga_predicted_cell_types.Rdata")
sva.sup.ga<- est_cell_counts
load("/big_data/reffree/adj.residuals.ruv.sex_predicted_cell_types.Rdata")
ruv.sex<- est_cell_counts
load("/big_data/reffree/adj.residuals.ruv.ga_predicted_cell_types.Rdata")
ruv.ga<- est_cell_counts
load("/big_data/reffree/adj.residuals.reffreecellmix_predicted_cell_types.Rdata")
cellmix<- est_cell_counts
load("/big_data/reffree/adj.residuals.refactor_predicted_cell_types.Rdata")
refactor<- est_cell_counts
load("/big_data/reffree/facs_predicted_cell_types.Rdata")
facs.counts<- est_cell_counts
load("/big_data/reffree/facs_pcs_predicted_cell_types.Rdata")
facs.pcs.counts<- est_cell_counts
load("/big_data/reffree/decon_predicted_cell_types.Rdata")
decon.counts<- est_cell_counts
load("/big_data/reffree/decon_pcs_predicted_cell_types.Rdata")
decon.pcs.counts<- est_cell_counts

load("/big_data/reffree/Louie_predicted_WB_celltypes_Oct27_use_Louies_sorted.rdata")
uncorrected<- est_cell_counts
plot.counts<- melt(rbind(cbind(as.data.frame(uncorrected), Method="uncorrected"),
                         cbind(as.data.frame(facs.counts), Method="FACS_counts"),
                         cbind(as.data.frame(facs.pcs.counts), Method="FACS_PCs"),
                         cbind(as.data.frame(decon.counts), Method="Decon_counts"),
                         cbind(as.data.frame(decon.pcs.counts), Method="Decon_PCs"),
                         cbind(as.data.frame(sva.unsup.sex), Method="sva.unsup.sex"),
                         cbind(as.data.frame(sva.unsup.ga), Method="sva.unsup.ga"),
                         cbind(as.data.frame(sva.sup.ga), Method="sva.sup.ga"),
                         cbind(as.data.frame(sva.sup.sex), Method="sva.sup.sex"),
                         cbind(as.data.frame(ruv.sex), Method="ruv.sex"),
                         cbind(as.data.frame(ruv.ga), Method="ruv.ga"),
                         cbind(as.data.frame(cellmix), Method="cellmix"),
                         cbind(as.data.frame(refactor), Method="refactor")
), id="Method")


levels(plot.counts$Method)<-c("Uncorrected","FACS - Drop One Cell Type","FACS - PCA - Gold-Standard",
                              "Deconvolution - Drop One Cell Type","Deconvolution - PCA","SVA - Unsupervised Sex",
                              "SVA - Unsupervised GA","SVA - Supervised GA","SVA - Supervised Sex",
                              "RUV - Sex","RUV - GA",  "RefFreeCellMix", "ReFACTor")

ggplot(plot.counts, aes(Method, value, fill=Method))+
  geom_point(shape=21, color="black", position = position_jitter(width = 0.1))+
  facet_wrap(~variable, ncol=2)+
  theme_bw()+
  fillscale+xlab("")+ylab("Predicted Cell Count from Deconvolution")+th+
  theme(axis.text.y=element_text(size=12,color="black"),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave("figures/Figure4decon.pdf", width = 9, height = 11, units = "in")


```
\pagebreak

\newpage
```{r deconvolutionmad, fig.width=12,  fig.height=10, echo=FALSE,  message=FALSE, fig.cap='Median absolute deviation (MAD) of predicted cell type counts from deconvolution. Boxes are coloured by the discretized MAD value to highlight method performance. '}


mads<- data.frame(FACS_counts=apply(facs.counts, 2, mad),
                  FACS_pcs=apply(facs.pcs.counts, 2, mad),
                  Decon_counts=apply(decon.counts, 2, mad),
                  Decon_pcs=apply(decon.pcs.counts, 2, mad),
                  sva.unsup.sex= apply(sva.unsup.sex, 2, mad),
                  sva.unsup.ga= apply(sva.unsup.ga, 2, mad),
                  sva.sup.sex= apply(sva.sup.sex, 2, mad),
                  sva.sup.ga= apply(sva.sup.ga, 2, mad),
                  ruv.sex= apply(ruv.sex, 2, mad),
                  ruv.ga= apply(ruv.ga, 2, mad),
                  cellmix= apply(cellmix, 2, mad),
                  refactor=apply(refactor, 2, mad),
                  uncorrected=apply(uncorrected, 2, mad)

)

mads$celltypes<- rownames(mads)
mads.melt<- melt(mads, id="celltypes")

mads.melt$col_mad<-cut(mads.melt$value, c(0,0.005, 0.01,0.05,0.1), right=FALSE, labels=c("<0.005","<0.01","<0.05",">0.05"))

levels(mads.melt$variable)<-c("FACS - Drop One Cell Type","FACS - PCA - Gold-Standard",
                              "Deconvolution - Drop One Cell Type","Deconvolution - PCA","SVA - Unsupervised Sex",
                              "SVA - Unsupervised GA","SVA - Supervised Sex","SVA - Supervised GA",
                              "RUV - Sex","RUV - GA",  "RefFreeCellMix", "ReFACTor","Uncorrected")

ggplot(mads.melt, aes(celltypes, variable, fill=col_mad))+
  geom_tile(color = "black",size=0.5)+
  geom_text(aes(label = round(value, 3)), size=5) +
  theme_bw()+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_blank())+
  scale_fill_manual(values=c("#084594","#4292c6","#9ecae1","#deebf7"), name="Cell Count MAD")+th+
   theme(axis.text.y=element_text(size=12,color="black"),
        axis.text.x = element_text(size=12,color="black",angle = 90, hjust = 1),
        panel.border = element_blank(),
        axis.ticks=element_blank())+xlab("")+ylab("")

ggsave("figures/Figure5decon.pdf", width = 12, height = 10, units = "in")
```
\pagebreak

\newpage
```{r, echo=FALSE,  message=FALSE}
sex_table<-read.csv("Sex_EWAS_hit_tables.csv")
colnames(sex_table)<-c("Method","Hits","True Positives","False Positives","False Negatives","Spearman","Kendall" )
levels(sex_table$Method)<-c("Deconvolution - PCA","Deconvolution - Drop One Cell Type",
                            "FACS - PCA - Gold-Standard","FACS - Drop One Cell Type",
                            "ReFACTor","RefFreeCellMix","RUV","SVA - Supervised","SVA - Unsupervised","Uncorrected")

sex_table$Spearman<-round(sex_table$Spearman, 3)
sex_table$Kendall<-round(sex_table$Kendall, 3)

sex_table[1,3:7]<-"-"

kable(sex_table, format="latex", booktabs = T, caption = "Comparison of cell type correction methods through EWAS results. EWAS was performed for sex on each corrected dataset. True and false positives and negatives were cvalculated in comparison to the gold-standard FACS - PCA correction. Spearman is the correlation coefficient for all CpG p values, and Kendall is the rank correlation coefficient for the top 1000 CpG p values.")%>%
  kable_styling(font_size = 7,(latex_options = c("HOLD_position")))

```
\pagebreak


